---
language: python

python:
    - "3.6"

env:
    - TRAVIS=1

services:
    - mongodb

install:
    - pip install -r requirements.txt -r requirements-dev.txt -e .
    - pip install coverage

script:
    - py.test -rxs tests/

notifications:
    email: false

after_success:
    - coveralls
