---
language: python

python:
    - "3.6"

env:
    - TRAVIS=1

services:
    - mongodb

install:
    - pip install --upgrade pip
    - pip install git+https://github.com/Clinical-Genomics/patient-similarity
    - pip install -r requirements.txt -r requirements-dev.txt .

script:
    - py.test -rxs --cov=patientMatcher tests/

notifications:
    email: false

after_success:
    - coveralls
