---
language: python

python:
    - "3.7"

env:
    - TRAVIS=1

services:
    - mongodb

install:
    - pip install -r requirements.txt -r requirements-dev.txt .

script:
    - py.test -rxs --cov=patientMatcher tests/

notifications:
    email: false

after_success:
    - coveralls
