---
language: python

python:
    - "3.6"

env:
    - TRAVIS=1

services:
    - mongodb

script:
    - py.test -rxs tests/

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt -e .

notifications:
    email: false
