coverage:
  status:
    patch: false
    project:
      default:
        # basic
        target: auto
        threshold: 0.5%
        base: auto
        paths:
          - "patientMatcher"
       # advanced settings
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
