version: '3'
# usage:
# sudo docker-compose up
services:
  mongodb:
    # Using the official MongoDB image 4.4.9
    image: mongo:4.4.9
    container_name: mongodb
    networks:
      - pmatcher-net
    ports:
      - '27013:27017'
    expose:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: admin
    volumes: # Invoke an init script that creates an authenticated user for the database
      - ./containers/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  pmatcher-cli:
    container_name: pmatcher-cli
    build: .
    environment:
      MONGODB_HOST: mongodb
      PMATCHER_CONFIG: '/home/worker/app/patientMatcher/patientMatcher/instance/config.py'
    depends_on:
      - mongodb
    networks:
      - pmatcher-net
    command: bash -c "pmatcher add demodata"

  pmatcher-web:
    container_name: pmatcher-web
    build: .
    environment:
      MONGODB_HOST: mongodb
      PMATCHER_CONFIG: '/home/worker/app/patientMatcher/patientMatcher/instance/config.py'
    depends_on:
      - mongodb
    networks:
      - pmatcher-net
    ports:
      - '9020:9020'
    expose:
      - '9020'
    command: bash -c 'pmatcher run --host 0.0.0.0 -p 9020'

networks:
  pmatcher-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
