###########
# BUILDER #
###########
FROM ghcr.io/astral-sh/uv:python3.12-bookworm AS python-builder

WORKDIR /app

# Copy the project files needed to configure dependencies build into the image
COPY --chmod=644 pyproject.toml uv.lock README.md ./

RUN uv venv --relocatable
RUN uv sync --frozen --no-install-project --no-editable

#########
# FINAL #
#########
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN groupadd --gid 1000 worker && useradd -g worker --uid 1000 --shell /usr/sbin/nologin --create-home worker

ENV PATH="/home/worker/app/.venv/bin:$PATH"

WORKDIR /home/worker/app

COPY --chown=root:root --chmod=755 . /home/worker/app
COPY --chown=root:root --chmod=755 --from=python-builder /app/.venv /home/worker/app/.venv

RUN uv pip install --no-cache-dir --editable .

ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8
ENV VIRTUAL_ENV=/home/worker/venv
ENV PATH="/home/worker/venv/bin:$PATH"

USER worker

CMD ["uv, "run", gunicorn", \
     "--workers=1", \
     "--threads=1", \
     "--bind=0.0.0.0:8000", \
     "--timeout=400", \
     "--proxy-protocol", \
     "--forwarded-allow-ips=10.0.2.100,127.0.0.1", \
     "--log-syslog", \
     "--access-logfile=-", \
     "--error-logfile=-", \
     "--log-level=debug", \
     "patientMatcher.server.auto:app"]





