version: '3'
# usage:
# sudo docker-compose up
services:
  mongodb:
    # Lightweight Docker image for MongoDB which makes it easy to create:
    # - admin
    # - database
    # - database user with password
    # when the container is first launched.
    image: vepo/mongo
    container_name: mongo
    networks:
      - pmatcher-net
    environment:
      - AUTH=y
      - ADMIN_USER=root
      - ADMIN_PASS=admin123
      - APPLICATION_DATABASE=pmatcher
      - APPLICATION_USER=pmUser
      - APPLICATION_PASS=pmPassword
    ports:
      - '27017:27017'
    expose:
      - '27017'

  pmatcher-cli:
    container_name: pmatcher-cli
    build:
      context: .
      dockerfile: Dockerfile
    image: clinicalgenomics/patientmatcher
    environment:
      MONGODB_HOST: mongodb
      PMATCHER_CONFIG: '/home/worker/app/patientMatcher/patientMatcher/instance/config.py'
    container_name: pmatcher-cli
    depends_on:
      - mongodb
    networks:
      - pmatcher-net
    command: bash -c "pmatcher add client -id test_client -token custom_token -url custom_url && pmatcher add demodata --ensembl_genes"

  pmatcher-web:
    container_name: pmatcher-web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pmatcher-web
    environment:
      MONGODB_HOST: mongodb
      PMATCHER_CONFIG: '/home/worker/app/patientMatcher/patientMatcher/instance/config.py'
    depends_on:
      - mongodb
    networks:
      - pmatcher-net
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: bash -c 'pmatcher run --host 0.0.0.0'

networks:
  pmatcher-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
