###########
# BUILDER #
###########

FROM ghcr.io/astral-sh/uv:python3.12-bookworm AS builder

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN python3 -m venv /home/worker/venv \
 && . /home/worker/venv/bin/activate \
 && uv sync --frozen --no-install-project --no-editable

COPY . .

#########
# FINAL #
#########

FROM ghcr.io/astral-sh/uv:python3.12-bookworm AS deployer

RUN groupadd --gid 1000 worker && useradd -g worker --uid 1000 --create-home worker

RUN mkdir -p /home/worker/app
WORKDIR /home/worker/app

COPY --chown=worker:worker --from=builder /home/worker/venv /home/worker/venv
COPY --chown=worker:worker . .

ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8
ENV VIRTUAL_ENV=/home/worker/venv
ENV PATH="/home/worker/venv/bin:$PATH"

USER worker

CMD ["gunicorn", \
     "--workers=1", \
     "--threads=1", \
     "--bind=0.0.0.0:8000", \
     "--timeout=400", \
     "--proxy-protocol", \
     "--forwarded-allow-ips=10.0.2.100,127.0.0.1", \
     "--log-syslog", \
     "--access-logfile=-", \
     "--error-logfile=-", \
     "--log-level=debug", \
     "patientMatcher.server.auto:app"]





