site_name: PatientMatcher documentation

nav:
    - Home: index.md
    - Docker-based application: docker_app.md
    - Installing the application on a conda environment: conda_inst.md
    - Data types: data_types.md
    - Command line interface: cli.md
    - Server endpoints: endpoints.md
    - Matching algrorithm: algorithm.md
    - Matching notifications: matching_emails.md
    - Server error notifications: error_emails.md




theme: readthedocs
