name: Black check

on: [pull_request]

jobs:
  black-check:
    runs-on: ubuntu-latest
    name: black
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: install black
        run: |
          pip install black==22.3.0
      - name: run black
        run: |
          black . --check --line-length 100
