name: Publish main image and server image to Docker Hub

on:
 release:
  types:
   - created

jobs:
  docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:
    - name: Check out git repository
      uses: actions/checkout@v4

    - name: Publish main image (Dockerfile) to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: clinicalgenomics/patientmatcher
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.event.release.tag_name }}"

    - name: Publish server image (Dockerfile-server) to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: clinicalgenomics/patientmatcher-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-server
        tags: "latest,${{ github.event.release.tag_name }}"
