name: Tests and coverage
on: [push, pull_request]
jobs:
  Pytest_Codecov:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        mongodb-version: ['3.2', '4.4', '5.0']
    env:
      PMATCHER_CONFIG: ../instance/config.py

    steps:
    - uses: actions/checkout@v2
    - name: Launch MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongoDBVersion: ${{ matrix.mongodb-version }}
        mongodb-root-username: root
        mongodb-root-password: root123
      options: -v ./containers/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8

    - name: Install repo and its dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .
        pip install pytest
        pip install pytest-cov

    - name: Run pytest and codecov
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
