name: Tests and coverage
on: [pull_request]
jobs:
  Pytest_Codecov:
    runs-on: ubuntu-18.04
    env:
      PMATCHER_CONFIG: ../instance/config.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install repo and its dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install git+https://github.com/Clinical-Genomics/patient-similarity
        pip install -e .
        pip install pytest
        pip install pytest-cov
    - name: Run pytest and codecov
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
