name: pytest & codecov

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry to not create virtualenvs
        run: poetry config virtualenvs.create false --local

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Show directory structure for debugging
        run: |
          pwd
          ls -l
          ls -l patientMatcher/instance

      - name: Run tests with pytest
        working-directory: patientMatcher
        run: poetry run pytest ../tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
